### ISSUE TITLE
please include hash table randomization

### ISSUE THREAD

**Issue by dkg** [bmwiedemann/theunreproduciblepackage#2]
many interpreted languages offer randomized hash tables as a defense against DoS (see [oCERT-2011-003](http://www.ocert.org/advisories/ocert-2011-003.html) for more discussion).

If a build process depends on output from such a randomized hash, it can be non-reproducible.  for example:

```
0 dkg@alice:~$ python -R -c 'a = {"x": 1, "y": 2}; print a'
{'x': 1, 'y': 2}
0 dkg@alice:~$ python -R -c 'a = {"x": 1, "y": 2}; print a'
{'y': 2, 'x': 1}
0 dkg@alice:~$ 
```

The correct approach when a build process depends on output from a hash is to sort the keys of the hash and explicitly output it in the order of the keys.

It would be great to include this example in theunreproduciblepackage.

**Comment by lamby** [comment]
Note that python3 has deterministic keys in some situations.
